use_frameworks!

platform :ios, '8.0'

target 'SSCountDownButton_Example' do
  pod 'SSCountDownButton', :path => '../'

  target 'SSCountDownButton_Tests' do
    inherit! :search_paths

    
  end
end
